conf_title: AI Frontiers Conference
conf_theme: Deep Learning and Beyond
conf_date: November 3-5, 2017
conf_venue: Santa Clara Convention Center, California

favicon: /images/favicon.png
logo: /images/logo-horizontal.png

# Google Analytics:
ga: UA-88635436-2

# Copyright Infomation
startyear: 2017

# Quote for subscribe
quote: Join our mailing list to hear updates

slogan: Speeches from our previous conference.
